<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/Base.Master" AutoEventWireup="true" CodeBehind="default.aspx.cs" Inherits="CamillaMorton.about._default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="Stylesheet" type="text/css" href="/resources/css/content.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div id="Biography" class="cf">
    <p class="photo smallprint"><img src="/resources/images/camilla-morton.jpg" alt="Camilla Morton by Andrew Lamb" /><br />Photo by Andrew Lamb</p>
    
    <p><strong>Background/academic – how did you get to where you are now?</strong></p>
    <p>However much you want to plan things I don't think you ever really can. I started off at an all girl's school, was very quiet, very shy, wanted to be a pianist. I got into art, started painting and next thing you know was at Art College. I went to Central Saint Martins to study fashion – a cliché I know – my mum used to let me cut up old copies of Vogue when I was growing up – so I guess it was inevitable, because before I knew it I was working in fashion.</p>
    <p>I did work experience while I was at college with everyone and anyone. I worked on cable TV, in PR, at The Telegraph and at Vogue&#8230; and then in my final year of college I applied for a job at Christian Dior in Paris and ended up graduating and moving over to assist John Galliano. I met Katie Grand in the Hotel Costes and she gave me the chance to work with her in London on the launch of her magazine POP. Lisa Armstrong gave me a column in The Times and it was these editors that started me off, and soon I started to freelance for various newspapers and magazines. All the while though I kept doing odds and ends for Galliano, I could never leave him&#8230; I have written for US and English magazines but what I love most is a toss up between John and covering the fashion shows&#8230;</p>
    <p>Basically I had several turning points in my life. One: seeing Galliano's first show. Two: Meeting Manolo who told me to work for John. Three: Meeting Galliano. And from this all else has stemmed. If you work hard, and wish even harder anything is possible.</p>
    
    <p><strong>What made you decide to write your first and current book?</strong></p>
    <p>Lots!! How to Walk in High Heels changed my life!! It turned out to be a real hit – I was really lucky – but also so surprised at how it captured people's imagination&#8230; I wrote the book because I had come to Paris to do the collections, had dashed round to see the boys in the studio, and been robbed&#8230; Let me explain as I know that sounds a bit dramatic! I had started to cover the shows, as a 'grown up' journalist, and that season arrived in Paris straight from Milan breathless to get to the studio to see everyone. I got to the hotel, dumped my luggage, went to Zara and bought not one but two jumpers, and unfolded my favourite pieces, the Alaia dress I really still couldn't afford, the heels, the notebooks and all the knick knacks I had accumulated on my trip, etc. I ran over to the studio with tales of my adventures in fashion, and then returned five minutes later to grab the gifts I had got on my travels in my haste to see them. Up the rickety old lift again to 602. Jabbed the key in the door, clicked on the light, and there was nothing. Nothing as in no clothes, no luggage, no passport, no suitcase, none of my stuff! I went down and up, opened the door (as if when I returned all would have magically returned) Crisis.</p>
    <p>I went back to the studio. I remember it so clearly! 'I don't want to work in fashion,' I sobbed to the boys as I tried to work out what I had lost, and indeed how I had lost it, and totally sabotaged any fittings getting done. Steven tried to jolly me out of my black cloud and gave me a pen and notepad and said they would help me come up with a new career. 'Write a list of things you like', said John, 'or things you don't,' said Steven, so to compromise we wrote a list of things I was hopeless at&#8230; all 250 things. 'This isn't making me feel any better!' I wailed, 'I am a victim of crime and now I am also rubbish at this whole list of things!!' 'No my Lala, you are going to write a book!' said John, and with that the black cloud vanished and everything seemed jolly again – and things were just the way you should be.</p>
    <p>Galliano has such an astounding optimism its as if his wishes are a magic command, and so that was how I came to do 'How to Walk in High Heels'. Next thing you know I had to follow it up. A sequel? John's PA looked pained (I had insisted I faxed him every draft of every chapter, and he had dutifully read each one, and even wrote the foreword). 'Well are you perfect yet?' they asked when I begged them to help me think of the next step. I blushed. I might not be 'perfect' in many ways, but sitting here in the studio it felt as if this was pretty close to my idea of heaven&#8230; Clearly they didn't agree. So I decided to create a Utopia for the ultimate girl to reach – not the 'perfect' girl, but the 'pretty darn close and happy about it' girl&#8230; Just as they would create a path for their muse to follow, I followed this formula and laid out a new city, a new month, a new adventure, and by the end she would be the ultimate 'Girl for All Seasons', just as I felt when I was in that room with them - I felt invincible. So yes, as well as my day job, 'A Year in High Heels' was published first in the UK and then in September 2007 in America. I am now working on a few new book ideas – fashion and onto fiction&#8230;</p>
    
    <p><strong>Your book seems to be a kind of guide to modern women. What are the essential rules that a woman of this age must be aware of?</strong></p>
    <p>Remember there are no rules – but there are so many ideas, opinions, options that I wanted to have a book that brought the main ones together. We all have such hectic lifestyles that sometimes your mind goes blank on the most crucial thing. I wanted a book that was a guide and a best friend that would help you navigate through all the nightmares I wanted to learn how to do too&#8230; I think that women are expected to be so much to so many – its not surprising that sometimes you want a refresher, and also that you want to be the best at all you do. This is a book about looking good and feeling good – a very old method, just newer names and labels!</p>
    
    <p><strong>What have you learned from your book. I mean what is the best part of being a writer and especially a writer who guides her audiences?</strong></p>
    <p>The best part is how much I learnt and how much I continue to learn!! How amazing my friends have been and how if you set your mind to it anything is possible – I never thought I would write a book but now here I am planning more!!</p>
    
    <p><strong>All those famous names that are mentioned in your book are your friends right? What can you tell about John Galliano, Gisele Bundchen and Manolo Blahnik as a friend?</strong></p>
    <p>You have picked three of my dearest friends. Manolo has been a mentor and a true guardian angel, Gisele is even more beautiful in the flesh as she has such an amazing spirit and is such a real and true friend and John Galliano is beyond expectation, description, imagination – he made my world Technicolor. He is loyal, fun, hardworking but also the nearest to a genius I have ever been. I have worked with him for over a decade and there has never been one day when I haven't been dazzled by his personality, friendship and incredible talent. It is extraordinary that someone ordinary like me has such extraordinary friends. I am very lucky. I guess being around greatness makes you feel invincible and feel like you can push yourself to your limits and try and suceed in something you didn't know you could, I guess this is the message behind the book as much as how I live&#8230;</p>
</div>
</asp:Content>
